server:
  port: 8080
spring:
  application:
    name: springAI
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # Nacos 注册中心地址
#        server-addr: 172.28.127.10:8848   # Nacos 注册中心地址
      config:
        import-check:
          enabled: false

  data:
    redis:
      host: localhost
      port: 6379
      password:
  datasource:
    dynamic:
      primary: master
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        connectTimeout: 30000
        socketTimeout: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: root
          # 从库数据源
          # slave:
          #   driver-class-name: com.mysql.cj.jdbc.Driver
          #   url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          #   username: root
          #   password: root
  ai:
    openai:
      chat:
        api-key: ${OPENAI_API_KEY2}
        base-url: ${OPENAI_BASE_URL2}
        options:
          model: glm-5
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
          username: root
          password:
        database-name: default
        collection-name: test_agent_docs
        initialize-schema: true
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: COSINE

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.springai.mapper
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full

logging:
  level:
    org.springframework.web.client: DEBUG
    org.springframework.ai: DEBUG
    com.openai: DEBUG
